#init container

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: jsns
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: tomcat
    ports:
    - containerPort: 8080
  initContainers:
  - name: init-busybox
    image: busybox
    command: ['sh', '-c', 'sleep 60']
  - name: init-alpine
    image: alpine
