- name: Just ping and print
  hosts: localhost
  connection: local
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world


- name: Example ansible playbook
  hosts: all
  # become: true
  tasks:
     - name: Creates directory structure
       ansible.builtin.file:
          path: ~/ansible-practice/day/jai-test
          #   path: /tmp/jai-test5
          state: directory
          mode: '0755'

#----------------------> cratafl.yml

- name: Create a file under tmp
  hosts: all
  tasks:
     - name: Create a file
       file:
          path: /tmp/jssudha.txt
          state: touch


- name: del dir
  become: true
  hosts: all
  tasks:
     - name: Del dir
       file:
          path: /tmp/js
          state: absent
          #recurse: yes


---
- name: Install Nginx
  hosts: all
  become: yes 

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

---
- name: UnInstall Nginx
  hosts: all
  become: yes 

  tasks:
    - name: UnInstall Nginx
      apt:
        name: nginx
        state: absent

    - name: Remove Nginx configuration files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/nginx
        - /var/log/nginx
        - /var/cache/nginx
        - /var/www/html


- name: Install Apache
  hosts: apacheservers
  become: true
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present
  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes

