name: Deploy Project
on: [push, workflow_dispatch] #workflow_dispatch : it allows us to manually trigger
jobs:
    test: #name can be anything. 
        runs-on: ubuntu-latest
        steps:
            - name: Get code - for teting 
              uses: actions/checkout@v3
    deploy: #we can give any name
        needs: test #This way it will sequentially exectues. Else parallel
        # Here, we can give multiple jobs too. [test1, test2]
        runs-on: ubuntu-latest
        steps:
            - name: Get code - for deployment
              uses: actions/checkout@v3