name: Deploy Project
on: [push, workflow_dispatch] #workflow_dispatch : it allows us to manually trigger
jobs:
    test: #name can be anything. 
        runs-on: ubuntu-latest
        steps:
            - name: Get code - for teting 
              run: echo "Executing the Job - Testing"
              #uses: actions:checkout@v3
    deploy: #we can give any name
        needs: test #This way it will sequentially exectues. Else parallel
        # Here, we can give multiple jobs too. [test1, test2]
        runs-on: ubuntu-latest
        steps:
            - name1: Get code - for deployment
              run: echo "Executing the Job - deployment"
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Github context
              run: echo "${{toJson(github)}}"
    