name: Test project
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code #download the code from repo
              uses: actions/checkout@v3 #uses to use action. 
            - name: Install NodeJs
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: Install dependencies
              run: npm ci #install all dependencies 
            - name: Run tests
              run: npm test